# Generated by Django 2.0.7 on 2018-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20181001_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='网址'),
        ),
    ]
