# Generated by Django 2.0.7 on 2018-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20181001_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='home_display',
            field=models.BooleanField(default=True, verbose_name='首页显示'),
        ),
        migrations.AlterField(
            model_name='column',
            name='nav_display',
            field=models.BooleanField(default=True, verbose_name='导航显示'),
        ),
    ]
