# Generated by Django 2.0.7 on 2018-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20181001_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=200, unique=True, verbose_name='网址'),
        ),
    ]
